### ISSUE TITLE
What value indicates tumor cfDNA fraction?

### ISSUE THREAD

**Issue by rgranit** [tgac-vumc/ACE#1]
ACE seems like a great tool. I've ran 'ploidyplotloop' on QDNAseq object and got the output, but I'm not quite sure where do I find the tumor DNA estimate.. can you please give me a tip?

**Comment by jpoell** [comment]
ploidyplotloop and runACE (which itself runs ploidyplotloop) write files. A summary of estimates for all samples can be found in the fitpicker.tsv file (with best estimate given when autopick=TRUE). When using only CNA data, there is often not a single clear best estimate, so it is usually necessary to manually curate individual cases, although large data sets show that in general ACE performs really well (see Bioinformatics paper). 

When analyzing in an R session, two functions return estimates for tumor purity: singlemodel() and squaremodel(). singlemodel() assumes a fixed ploidy, and squaremodel() fits using a variable ploidy. For samples with a "wild" copy number profile the latter generally gives better results. Both these functions give a graphic representation of fits and their associated (relative) error. They also return a list object. In singlemodel the purities of the estimates are given in $minima, whereas for squaremodel they are given in the $minimadf (they also show the associated ploidy).
