### ISSUE TITLE
RFE: Allow feeding the models back into the QDNAseq object they were generated from

### ISSUE THREAD

**Issue by lbeltrame** [tgac-vumc/ACE#2]
Hello,

I think it would be worthwhile to be able to feed the fitted models (once the likely fit has been chosen by the user) for a sample group back in the `segmented` assayDataElement of the QDNAseq object. 

The rationale is that some additional analysis tools make use of QDNAseqCopyNumbers objects, and they would benefit by ACE's modeling (I have a few problematic samples where the modeling done by ACE improves the situation). Currently this is not possible unless done manually.

**Comment by jpoell** [comment]
Yes that is a good point! I would have to brush up on my S4 object programming for this, and I will not have time for this in the foreseeable future. Sounds like a very nice bioinformatics student project!
