### ISSUE TITLE
RFE: produce a .seg file by processing multiple samples with fitpicker.tsv

### ISSUE THREAD

**Issue by lbeltrame** [tgac-vumc/ACE#3]
Like with #2, the rationale is to have a "corrected" segment file which can be then used downstream with other tools (like GISTIC). There is currently no way to do this in batch, because `postanalysisloop` only creates single files. Also the segment files are in copy number, and not in log2ratio, which is what it is needed by GISTIC and other tools.

In short, a hypotetical approach would use fits from the `fitpicker.tsv` file to generate segments with `getadjustedsegments` and collapse them in a single file to be saved afterwards.

**Comment by jpoell** [comment]
Indeed.

**Comment by lbeltrame** [comment]
I was actually able to do so (and the whole thing I used ACE for ended up netting me a publication, neat!) with some small-scale Python hackery after saving the results with ACE. At the same time I was able to convert the results back to log2 (using the estimated ploidy) to use for downstream applications (think GISTIC).

**Comment by jpoell** [comment]
Well done on the publication! Again I am sorry I did not spot the question earlier, but I am glad you managed a workaround yourself. Gotta say, I often find myself in these situations where it takes some creating coding to parse files into the appropriate format for some other software tool.

Best,

Jos
