### ISSUE TITLE
'Realloc' could not re-allocate memory (18446744065128005632 bytes)

### ISSUE THREAD

**Issue by shashwatsahay** [tgac-vumc/ACE#4]
Hi 

I keep getting this error everytime I try to run  ACE

I am using R 4.1.0 inside a conda environment

All other dependent packages were directly downloaded using biocManger

```
Loaded bin annotations for genome ‘hg19’, bin size 100 kbp, and experiment type ‘SR50’ from annotation package QDNAseq.hg19 v0.99.2
    tumor-bone-marrow-0X_XXX_merged.mdup (1 of 1): extracting reads ...Error in value[[3L]](cond) :
  'Realloc' could not re-allocate memory (18446744065128005632 bytes)
  file: /pathtobam/tumor-bone-marrow-0X_XXX_merged.mdup.bam
  index: NA
Calls: runACE ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by jpoell** [comment]
Sorry I was not notified and have only responded to direct e-mails! This seems to be a QDNAseq problem, and it seems to have to do with the extreme memory allocation. It must be something about the bam file, but I can't imagine the size of it is several thousand petabytes. Unfortunately it is quite complicated (for me) to figure out how QDNAseq processes the bam-files, so I would suggest contacting them. I would suggest to provide some info on the bam-file (size, reads, perhaps even the header)

**Comment by shashwatsahay** [comment]
Hi 


I just had a look at QDNAseq apparently we need to pass chumksize to bin count will have a look

https://github.com/ccagc/QDNAseq/issues/100
