### ISSUE TITLE
Missing X and Y chromosomes in the segfile

### ISSUE THREAD

**Issue by l0ka** [tgac-vumc/ACE#7]
Hi, first of all thank you for developing this great package. I'm currently running it on a tumor BAM file, from an ultra-low coverage WGS experiment. Here's the code:
```
runACE(inputdir       = in.dir, 
       filetype       = "bam", 
       binsizes       = c(100, 500, 1000), 
       ploidies       = c(2, 4), 
       imagetype      = "pdf", 
       outputdir      = out.dir, 
       genome         = "hg38", 
       method         = "RMSE", 
       printsummaries = TRUE, 
       savereadcounts = FALSE, 
       autopick       = TRUE, 
       penalty        = 0, 
       cap            = 12, 
       bottom         = 0, 
       trncname       = FALSE
       )
```
Then I proceed with the manual inspection (to be short I omitted the steps where I look at the error models and plots):

```
object <- readRDS(file.path(out.dir, "1000kbp.rds"))

template <- objectsampletotemplate(copyNumbersSegmented = object, 
                                   index                = 1
                                   )
```
And finally I get the segfile:
```
segmentdf <- getadjustedsegments(template    = template, 
                                 cellularity = 0.33, 
                                 sgc         = c("X", "Y"), 
                                 log         = FALSE, 
                                 ploidy      = 2.32
                                 )
```
The problem is there are only chromosome 1-22, while X and Y are missing (I'm analyzing prostate cancer data, therefore males only). I'm particularly interested in the copy number segments in chromosome X. Additionally, I tried the `postanalysisloop` function:
```
postanalysisloop(copyNumbersSegmented = object, 
                 modelsfile           = modelsfile, 
                 printsegmentfiles    = TRUE, 
                 onlyautosomes        = FALSE, 
                 printnewplots        = TRUE, 
                 imagetype            = "pdf", 
                 outputdir            = out.dir2, 
                 segext               = "tsv", 
                 genderci             = 17, 
                 trncname             = FALSE 
                 )
```
But still no X and Y chromosomes. From the documentation it's not entirely clear to me what happened. What am I missing? Thank you in advance.

**Comment by jpoell** [comment]
Sorry for the late reply! Although there is support for sex chromosomes in most functions, the entire pipeline wrapper runACE does not provide this functionality. The problem is that you might introduce a bias between men and women. That said, I often make my final CNPs with sex chromosomes anyway, and in some cases it can even help finding the correct fit (again, that only works in samples with 1 copy X and Y, hence the bias). To go about that, I run the QDNAseq code differently! This is nicely described in the vignette of QDNAseq.

**Comment by l0ka** [comment]
Thank you for the clarification! I guess you can close this issue.
