### ISSUE TITLE
segment file from other software compatible？

### ISSUE THREAD

**Issue by Tesson98** [tgac-vumc/ACE#8]
Dear @jpoell,
       Thanks for developing this useful tool. 
       I recently got segment files of ~100 WGS sample (with unkown purity)  using CNVkit and want to infer absolute copy number using ACE. However, it was noted **"For this it uses segmented data from the QDNAseq package, which in turn uses a number of dependencies to turn mapped reads (in bam-files) into segmented data"**. So I wondered if the segment files generated by other software(not QDNAseq) compatible for the input of ACE？
       Really hope for your advices and wish you a good day!

Tesson,
6th,Feb,2023

**Comment by jpoell** [comment]
Hi Tesson,
Thanks for using the package. Indeed I have written some custom scripts to directly do model fitting from segment data, and these are not in the package yet. I suppose I should consider adding them. I have them in the file below, but they are not documented, just a few sparse instructions in the comments. These will directly work on your segment files (they can also handle log-transformed data, for which there is an argument in the function.
[segment_functions.zip](https://github.com/tgac-vumc/ACE/files/10663712/segment_functions.zip)

It is also possible to do it in the ACE package itself using the segmentstotemplate function. It creates fake bin data, but for purity fitting this does not matter. 

Good luck!

**Comment by Tesson98** [comment]
Thank you so much and I will try this.
